### ISSUE TITLE
光棱塔 光棱塔设计车 变换位置不匹配

### ISSUE THREAD

**Issue by valorad** [valorad/RA2YR-wc-s-Revenge#1]
日前测试发现光棱塔设计车展开为光棱塔后，位置向上向右偏移一个单元格，而光棱塔收起为光棱塔设计车后，位置向下向左偏移一个单元格。

**Comment by valorad** [comment]
尤里复仇里面没有这个问题，怀疑是RA2原版的引擎bug, so out dated.

**Comment by LinruoT** [comment]
# eruan

**Comment by valorad** [comment]
RA2 Engine bug. Will not fix, since it works well on YR.
